### ISSUE TITLE
Performance comparison between Blaze and Vectorclass

### ISSUE THREAD

**Issue by MarcusKlik** [ChingChuan-Chen/RcppBlaze#4]
Hi @ChingChuan-Chen, from the [Blaze wiki](https://bitbucket.org/blaze-lib/blaze/wiki/Benchmarks) I gather that `Blaze` is a pretty fast math library. Do you have an idea how it compares to Agners [vectorclass](http://www.agner.org/optimize/#vectorclass) library for basic operations?

I'm very interested because for my R package [`fst`](https://github.com/fstpackage/fst) I'm looking for a fast 
SIMD enabled math library and Blaze seems very suitable indeed as `fst` is also using OpenMP and will be using intrinsic soon (for bit-shifting and compression).

Thanks!

**Comment by ChingChuan-Chen** [comment]
I know that there is a performance test which is made by the authors of `Blaze`, so you can according to their items to compare two packages. You can find the `blazemark` at [cloned Blaze repository](https://github.com/ChingChuan-Chen/blaze/tree/master/blazemark/blazemark).

However, it is not a fair comparison in R. Because R doesn't support CBLAS or LAPACKE, `Blaze` and `Eigen` don't use the same BLAS/LAPACK library in comparison. Therefore, you can find out that Blaze is not so fast as expected for big size matrix ([link](https://github.com/ChingChuan-Chen/RcppBlaze/blob/master/inst/examples/lmBenchmark.R#L153)), but it is fastest for small size matrix ([link](https://github.com/ChingChuan-Chen/RcppBlaze/blob/master/inst/examples/lmBenchmark.R#L213)).  To make Blaze fast, I am working on importing CBLAS and LAPACKE to Rcpp ([link](https://github.com/ChingChuan-Chen/RcppLAPACKE)). RcppLAPACKE is coming soon.

PS: Armadillo, Eigen and Blaze do not use BLAS in small matrix.

**Comment by MarcusKlik** [comment]
Thanks a lot for that information! And very nice that you are working on an interface to CBLAS and LAPACKE. I will take a closer look at the benchmarks. For my use case I am most interested in vector operations (not matrices), so the basic operators, the bit-wise operators, some type casting and bit-shifters.

thanks again and good luck with your projects!
